/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_hotel;

/**
 *
 * @author ASUS
 */

import java.awt.HeadlessException;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
public class PesanKamar extends javax.swing.JFrame {
    Koneksi conn;
    Statement stm;
    /**
     * Creates new form NewJFrame
     */
    
    public PesanKamar() {
        initComponents();
        Statement stm;
        conn = new Koneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JKEL = new javax.swing.ButtonGroup();
        JKAM = new javax.swing.ButtonGroup();
        HOMEPACK = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        TANGGAL = new javax.swing.JComboBox<>();
        BULAN = new javax.swing.JComboBox<>();
        TAHUN = new javax.swing.JComboBox<>();
        Durasi = new javax.swing.JComboBox<>();
        LABELPRICE = new javax.swing.JLabel();
        buttonPesan = new javax.swing.JButton();
        VIP = new javax.swing.JRadioButton();
        VVIP = new javax.swing.JRadioButton();
        KING = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(224, 0, 255));

        HOMEPACK.setBackground(new java.awt.Color(185, 2, 2));
        HOMEPACK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("HOMEPAGE");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NAMA");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TANGGAL LAHIR");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DURASI MENGINAP");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("JENIS KAMAR");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("TOTAL HARGA");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(":");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(":");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(":");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText(":");

        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });

        TANGGAL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TANGGAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BULAN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BULAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        TAHUN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TAHUN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033" }));

        Durasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Durasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 DAY", "2 DAYS", "3 DAYS", "4 DAYS", "5 DAYS", "6 DAYS", "7 DAYS", "8 DAYS", "9 DAYS" }));

        LABELPRICE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LABELPRICE.setForeground(new java.awt.Color(255, 255, 255));
        LABELPRICE.setText(" ");
        LABELPRICE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        buttonPesan.setBackground(new java.awt.Color(255, 255, 255));
        buttonPesan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonPesan.setForeground(new java.awt.Color(185, 2, 2));
        buttonPesan.setText("PESAN");
        buttonPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesanActionPerformed(evt);
            }
        });

        JKAM.add(VIP);
        VIP.setText("VIP");

        JKAM.add(VVIP);
        VVIP.setText("VVIP");

        JKAM.add(KING);
        KING.setText("KING");

        javax.swing.GroupLayout HOMEPACKLayout = new javax.swing.GroupLayout(HOMEPACK);
        HOMEPACK.setLayout(HOMEPACKLayout);
        HOMEPACKLayout.setHorizontalGroup(
            HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMEPACKLayout.createSequentialGroup()
                .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HOMEPACKLayout.createSequentialGroup()
                            .addGap(268, 268, 268)
                            .addComponent(buttonPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(144, 144, 144))
                        .addGroup(HOMEPACKLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(HOMEPACKLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(52, 52, 52)
                                        .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(HOMEPACKLayout.createSequentialGroup()
                                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(VIP)
                                                .addGap(18, 18, 18)
                                                .addComponent(VVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(KING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(HOMEPACKLayout.createSequentialGroup()
                                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LABELPRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(HOMEPACKLayout.createSequentialGroup()
                                        .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(HOMEPACKLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HOMEPACKLayout.createSequentialGroup()
                                                .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel15))
                                                .addGap(30, 30, 30)
                                                .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(HOMEPACKLayout.createSequentialGroup()
                                                        .addComponent(TANGGAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(BULAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(TAHUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(22, 22, 22))))))
                    .addGroup(HOMEPACKLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel12)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        HOMEPACKLayout.setVerticalGroup(
            HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMEPACKLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel12)
                .addGap(88, 88, 88)
                .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TANGGAL, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BULAN)
                        .addComponent(TAHUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Durasi))
                .addGap(18, 18, 18)
                .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VIP)
                    .addComponent(VVIP)
                    .addComponent(KING))
                .addGap(18, 18, 18)
                .addGroup(HOMEPACKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELPRICE))
                .addGap(64, 64, 64)
                .addComponent(buttonPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HOMEPACK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HOMEPACK, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public LocalDate getBornDate(){
        LocalDate born = LocalDate.of(
            Integer.parseInt(TAHUN.getSelectedItem().toString()), 
            BULAN.getSelectedIndex()+1, 
            Integer.parseInt(TANGGAL.getSelectedItem().toString())
        );
        return born;
    }
    
    public String getJKAM(){
        if(KING.isSelected()) {
            return "King";
        }else if (VVIP.isSelected()){
            return "VVIP";
        } else {
            return "VIP";
        }
    }
    
    public void clearText(){
        inputNama.setText(null);
        JKAM.clearSelection();
    }
    
    private void buttonPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesanActionPerformed
        // TODO add your handling code here:
        try {
                    String sql = "INSERT INTO list_kamar (nama, tgl_lahir, durasi_nginep, jenis_kamar)"
                    + "VALUES ("
                    + "'" + inputNama.getText()         + "',"
                    + "'" + getBornDate()               + "',"
                    + "'" + Durasi.getSelectedItem()    + "',"
                    + "'" + getJKAM()                   + "'"
                    + ");";
                    conn.query(sql);
                    JOptionPane.showMessageDialog(null,"NAMA: " + inputNama.getText() + "\n"
                                                    + "\nTANGGAL LAHIR: " + getBornDate() + "\n"
                                                    + "\nDURASI MENGINAP: " + Durasi.getSelectedItem() + "\n"
                                                    + "\nDI KAMAR: " + getJKAM() + "\n" + "\n==================",                                                               
                                                    "PESANAN TERSIMPAN!" , javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    this.setState(1);
        } catch (HeadlessException ex) {
            System.err.println(ex.getMessage());
        }
        
       /* String NAMA, JENIS_KELAMIN, JENIS_KAMAR, DURASI_MENGINAP, TOTAL_HARGA;
        int TANGGAL_LAHIR;

        NAMA = jTextField1.getText();
        DURASI_MENGINAP = (String) LAMA.getSelectedItem();
        
        if(PRIA.isSelected()) {
            JENIS_KELAMIN = "PRIA";
        }
        else{
            JENIS_KELAMIN = "WANITA";
        }
        
        if(VIP.isSelected()) {
            JENIS_KAMAR = "VIP";
            TOTAL_HARGA = "3000000";
        }
        else if(VVIP.isSelected()){
            JENIS_KAMAR = "VVIP";
            TOTAL_HARGA = "5000000";
        }
        else{
            JENIS_KAMAR = "KING";
            TOTAL_HARGA = "9000000";
        }
        
        LABELPRICE.setText(TOTAL_HARGA);
        
        javax.swing.JOptionPane.showMessageDialog(this, "NAMA: " + NAMA + "\n"
                                                    + "\nJENIS KELAMIN: " + JENIS_KELAMIN + "\n"
                                                    + "\nDURASI MENGINAP: " + DURASI_MENGINAP + "\n"
                                                    + "\nDI KAMAR: " + JENIS_KAMAR + "\n" + "\n=================="
                                                    + "\nPEMBAYARAN: " + TOTAL_HARGA + "\n",
                                                   
                

                                                    "PESANAN TERSIMPAN!" , javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        LISTKAMAR lg = new LISTKAMAR();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(LISTKAMAR.EXIT_ON_CLOSE);

        this.setState(1);
        */
    }//GEN-LAST:event_buttonPesanActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesanKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BULAN;
    private javax.swing.JComboBox<String> Durasi;
    private javax.swing.JPanel HOMEPACK;
    private javax.swing.ButtonGroup JKAM;
    private javax.swing.ButtonGroup JKEL;
    private javax.swing.JRadioButton KING;
    private javax.swing.JLabel LABELPRICE;
    private javax.swing.JComboBox<String> TAHUN;
    private javax.swing.JComboBox<String> TANGGAL;
    private javax.swing.JRadioButton VIP;
    private javax.swing.JRadioButton VVIP;
    private javax.swing.JButton buttonPesan;
    private javax.swing.JTextField inputNama;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    // End of variables declaration//GEN-END:variables
}
